name: action_3.yml
on: [push, workflow_dispatch]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Run Test
        working-directory: gh-actions-1
        run: mvn test
  deploy:
    needs: [run]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GCP
        run: echo "Deploy..."
