name: action_5.yml
on:
  pull_request:
#    types: [opened, edited]
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
      # dev-new, dev-test, etc
      - 'dev-*'
    paths-ignore:
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploy..."
