name: action_3.yml
on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test
        working-directory: gh-actions-1
        run: mvn test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GCP
        run: "Deploy..."
