name: simple if statement
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "Hello"

      - name: if test
        # if: 1==1
        if: 1==0
        run: | 
          echo "if statement is ${{ 1==0 }}"
          exit 1

  report:
    needs: [test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: print error
        run: |
          echo "Something went wrong"
          echo "${{ github }}"
