name: Artifacts
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: actions/upload-artifact@v3
        with:
          name: deploy artifacts
          path: |
            text.txt