name: First Workflow

on: workflow_call

jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: |
          echo "Hello World!"
          echo "Simple action"
      - name: Print goodbye
        run: echo "Good bye!"
