name: Artifacts
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug working directory
        run: |
          echo "Current directory:"
          pwd
          ls -la

      - name: Deploy
        uses: actions/upload-artifact@v3
        with:
          name: deploy artifacts
          path: text.txt